<a href="https://colab.research.google.com/github/Saransh-Basu-01/Advanced-Pytorch/blob/main/Advanced_Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Indexing and Slicing

In [ ]:
import torch

# Create a 1D tensor
x_1d = torch.tensor([10, 11, 12, 13, 14])
print(f"Original 1D tensor:\n{x_1d}")

# Access the first element
first_element = x_1d[0]
print(f"\nFirst element (x_1d[0]): {first_element}, Type: {type(first_element)}")

# Access the last element
last_element = x_1d[-1]
print(f"Last element (x_1d[-1]): {last_element}")

# Modify an element
x_1d[1] = 110
print(f"\nModified tensor:\n{x_1d}")


Original 1D tensor:
tensor([10, 11, 12, 13, 14])

First element (x_1d[0]): 10, Type: <class 'torch.Tensor'>
Last element (x_1d[-1]): 14

Modified tensor:
tensor([ 10, 110,  12,  13,  14])


In [ ]:
# Create a 2D tensor (e.g., a small matrix)
x_2d = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(f"Original 2D tensor:\n{x_2d}")

# Access the element at row 0, column 1
element_0_1 = x_2d[0, 1]
print(f"\nElement at [0, 1]: {element_0_1}")

# Access the entire first row (index 0)
first_row = x_2d[0] # or x_2d[0, :]
print(f"\nFirst row (x_2d[0]): {first_row}")

# Access the entire second column (index 1)
second_col = x_2d[:, 1]
print(f"Second column (x_2d[:, 1]): {second_col}")

# Modify an element
x_2d[1, 1] = 55
print(f"\nModified 2D tensor:\n{x_2d}")


Original 2D tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Element at [0, 1]: 2

First row (x_2d[0]): tensor([1, 2, 3])
Second column (x_2d[:, 1]): tensor([2, 5, 8])

Modified 2D tensor:
tensor([[ 1,  2,  3],
        [ 4, 55,  6],
        [ 7,  8,  9]])


In [ ]:
# Create a 1D tensor
y_1d = torch.arange(10) # Tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original 1D tensor: {y_1d}")

# Select elements from index 2 up to (not including) index 5
slice1 = y_1d[2:5]
print(f"\nSlice y_1d[2:5]: {slice1}")

# Select elements from the beginning up to index 4
slice2 = y_1d[:4]
print(f"Slice y_1d[:4]: {slice2}")

# Select elements from index 6 to the end
slice3 = y_1d[6:]
print(f"Slice y_1d[6:]: {slice3}")

# Select every second element
slice4 = y_1d[::2]
print(f"Slice y_1d[::2]: {slice4}")

# Select elements from index 1 to 7, with a step of 2
slice5 = y_1d[1:8:2]
print(f"Slice y_1d[1:8:2]: {slice5}")

# Reverse the tensor
slice6 = y_1d.flip(dims=[0])
print(f"Reversed tensor using .flip(dims=[0]): {slice6}")


Original 1D tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Slice y_1d[2:5]: tensor([2, 3, 4])
Slice y_1d[:4]: tensor([0, 1, 2, 3])
Slice y_1d[6:]: tensor([6, 7, 8, 9])
Slice y_1d[::2]: tensor([0, 2, 4, 6, 8])
Slice y_1d[1:8:2]: tensor([1, 3, 5, 7])
Reversed tensor using .flip(dims=[0]): tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [ ]:
# Create a 3x4 tensor
x_2d = torch.tensor([[ 0,  1,  2,  3],
                     [ 4,  5,  6,  7],
                     [ 8,  9, 10, 11]])
print(f"Original 2D tensor:\n{x_2d}")

# Select the first two rows and columns 1 and 2
sub_tensor1 = x_2d[0:2, 1:3]
print(f"\nSlice x_2d[0:2, 1:3]:\n{sub_tensor1}")

# Select all rows, but only the last two columns
sub_tensor2 = x_2d[:, -2:]
print(f"\nSlice x_2d[:, -2:]:\n{sub_tensor2}")

# Select the first row, columns 1 to the end
sub_tensor3 = x_2d[0, 1:]
print(f"\nSlice x_2d[0, 1:]:\n{sub_tensor3}")

# Select rows 0 and 2 (using step), all columns
sub_tensor4 = x_2d[::2, :]
print(f"\nSlice x_2d[::2, :]:\n{sub_tensor4}")


Original 2D tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Slice x_2d[0:2, 1:3]:
tensor([[1, 2],
        [5, 6]])

Slice x_2d[:, -2:]:
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])

Slice x_2d[0, 1:]:
tensor([1, 2, 3])

Slice x_2d[::2, :]:
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])


In [ ]:
# Create a tensor
data = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(f"Original data tensor:\n{data}")

# Create a boolean mask (e.g., select elements greater than 3)
mask = data > 3
print(f"\nBoolean mask (data > 3):\n{mask}")

# Apply the mask
selected_elements = data[mask]
print(f"\nElements selected by mask:\n{selected_elements}")
print(f"Shape of selected elements: {selected_elements.shape}")

# Modify elements based on a condition
data[data <= 3] = 0
print(f"\nData after setting elements <= 3 to zero:\n{data}")


Original data tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Boolean mask (data > 3):
tensor([[False, False],
        [False,  True],
        [ True,  True]])

Elements selected by mask:
tensor([4, 5, 6])
Shape of selected elements: torch.Size([3])

Data after setting elements <= 3 to zero:
tensor([[0, 0],
        [0, 4],
        [5, 6]])


In [ ]:
# Select rows where the first column is greater than 2
row_mask = data[:, 0] > 2
print(f"\nRow mask (data[:, 0] > 2): {row_mask}")

selected_rows = data[row_mask, :] # Use ':' for selecting all columns in the chosen rows
# Or simply: data[row_mask] - PyTorch often infers the full row selection
print(f"\nRows where first column > 2:\n{selected_rows}")



Row mask (data[:, 0] > 2): tensor([False, False,  True])

Rows where first column > 2:
tensor([[5, 6]])


In [ ]:
x = torch.arange(10, 20) # Tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(f"Original 1D tensor: {x}")

indices = torch.tensor([0, 4, 2, 2]) # Note the repeated index 2
selected = x[indices]
print(f"\nSelected elements using indices {indices}: {selected}")

# For 2D tensors
y = torch.arange(12).reshape(3, 4)
# [[ 0,  1,  2,  3],
#  [ 4,  5,  6,  7],
#  [ 8,  9, 10, 11]]
print(f"\nOriginal 2D tensor:\n{y}")

# Select specific rows
row_indices = torch.tensor([0, 2])
selected_rows = y[row_indices] # Selects rows 0 and 2
print(f"\nSelected rows using indices {row_indices}:\n{selected_rows}")

# Select specific columns
col_indices = torch.tensor([1, 3])
selected_cols = y[:, col_indices] # Selects columns 1 and 3 from all rows
print(f"\nSelected columns using indices {col_indices}:\n{selected_cols}")

# Select specific elements using pairs of indices
row_idx = torch.tensor([0, 1, 2])
col_idx = torch.tensor([1, 3, 0])
selected_elements = y[row_idx, col_idx] # Selects (0,1), (1,3), (2,0) -> [1, 7, 8]
print(f"\nSelected specific elements using (row_idx, col_idx):\n{selected_elements}")


Original 1D tensor: tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Selected elements using indices tensor([0, 4, 2, 2]): tensor([10, 14, 12, 12])

Original 2D tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Selected rows using indices tensor([0, 2]):
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])

Selected columns using indices tensor([1, 3]):
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

Selected specific elements using (row_idx, col_idx):
tensor([1, 7, 8])


# Reshaping and Rearranging Tensors

In [1]:
import torch

# Create a contiguous tensor
x = torch.arange(12) # tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")
print(f"Is contiguous? {x.is_contiguous()}")

# Reshape using view()
y = x.view(3, 4)
print("\nTensor after view(3, 4):")
print(y)
print(f"New shape: {y.shape}")
print(f"Shares storage with x? {y.storage().data_ptr() == x.storage().data_ptr()}") # Check if they share memory
print(f"Is y contiguous? {y.is_contiguous()}")

# Try another view
z = y.view(2, 6)
print("\nTensor after view(2, 6):")
print(z)
print(f"New shape: {z.shape}")
print(f"Shares storage with x? {z.storage().data_ptr() == x.storage().data_ptr()}")
print(f"Is z contiguous? {z.is_contiguous()}")


Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
Is contiguous? True

Tensor after view(3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
New shape: torch.Size([3, 4])
Shares storage with x? True
Is y contiguous? True

Tensor after view(2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
New shape: torch.Size([2, 6])
Shares storage with x? True
Is z contiguous? True


/tmp/ipykernel_2112/2418447993.py:14: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(f"Shares storage with x? {y.storage().data_ptr() == x.storage().data_ptr()}") # Check if they share memory


In [2]:
# Using -1 for inference
w = x.view(2, 2, -1) # Infers the last dimension to be 3 (12 / (2*2) = 3)
print("\nTensor after view(2, 2, -1):")
print(w)
print(f"New shape: {w.shape}")


Tensor after view(2, 2, -1):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
New shape: torch.Size([2, 2, 3])


In [3]:
# Example of view() failing on a non-contiguous tensor
a = torch.arange(12).view(3, 4)
b = a.t() # Transpose creates a non-contiguous tensor
print(f"\nIs b contiguous? {b.is_contiguous()}")

try:
    c = b.view(12)
except RuntimeError as e:
    print(f"\nError trying b.view(12): {e}")



Is b contiguous? False

Error trying b.view(12): view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [4]:
# Using reshape() on the non-contiguous tensor 'b'
print(f"\nOriginal non-contiguous tensor b:\n{b}")
print(f"Shape of b: {b.shape}")
print(f"Is b contiguous? {b.is_contiguous()}")

# Reshape works even if 'b' is not contiguous
c = b.reshape(12)
print(f"\nTensor c after b.reshape(12):\n{c}")
print(f"Shape of c: {c.shape}")
print(f"Is c contiguous? {c.is_contiguous()}")

# Check if 'c' shares storage with 'b'. It likely won't because reshape probably copied.
print(f"Shares storage with b? {c.storage().data_ptr() == b.storage().data_ptr()}")

# Reshape can also infer dimensions with -1
d = b.reshape(2, -1) # Infers the last dimension to be 6
print(f"\nTensor d after b.reshape(2, -1):\n{d}")
print(f"Shape of d: {d.shape}")



Original non-contiguous tensor b:
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
Shape of b: torch.Size([4, 3])
Is b contiguous? False

Tensor c after b.reshape(12):
tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])
Shape of c: torch.Size([12])
Is c contiguous? True
Shares storage with b? False

Tensor d after b.reshape(2, -1):
tensor([[ 0,  4,  8,  1,  5,  9],
        [ 2,  6, 10,  3,  7, 11]])
Shape of d: torch.Size([2, 6])


In [5]:
# Create a 3D tensor (e.g., representing C, H, W)
image_tensor = torch.randn(3, 32, 32) # Channels, Height, Width
print(f"Original shape: {image_tensor.shape}") # torch.Size([3, 32, 32])

# Permute to (Height, Width, Channels)
permuted_tensor = image_tensor.permute(1, 2, 0) # Specify new order: Dim 1, Dim 2, Dim 0
print(f"Permuted shape: {permuted_tensor.shape}") # torch.Size([32, 32, 3])

# Permute usually returns a non-contiguous view
print(f"Is permuted_tensor contiguous? {permuted_tensor.is_contiguous()}")

# Permuting back
original_again = permuted_tensor.permute(2, 0, 1) # Back to C, H, W
print(f"Shape after permuting back: {original_again.shape}") # torch.Size([3, 32, 32])
print(f"Is original_again contiguous? {original_again.is_contiguous()}") # Might still be non-contiguous

# Check storage sharing
print(f"Shares storage with original? {original_again.storage().data_ptr() == image_tensor.storage().data_ptr()}")


Original shape: torch.Size([3, 32, 32])
Permuted shape: torch.Size([32, 32, 3])
Is permuted_tensor contiguous? False
Shape after permuting back: torch.Size([3, 32, 32])
Is original_again contiguous? True
Shares storage with original? True


In [6]:
# Make the permuted tensor contiguous
contiguous_permuted = permuted_tensor.contiguous()
print(f"\nIs contiguous_permuted contiguous? {contiguous_permuted.is_contiguous()}")

# Now view() can be used safely
flattened_permuted = contiguous_permuted.view(-1)
print(f"Shape after flattening: {flattened_permuted.shape}")



Is contiguous_permuted contiguous? True
Shape after flattening: torch.Size([3072])


# Joining and Splitting Tensors

In [7]:
import torch

# Create two tensors
tensor_a = torch.randn(2, 3)
tensor_b = torch.randn(2, 3)
print(f"Tensor A (Shape: {tensor_a.shape}):\n{tensor_a}")
print(f"Tensor B (Shape: {tensor_b.shape}):\n{tensor_b}\n")

# Concatenate along dimension 0 (rows)
# Resulting shape: (2+2, 3) = (4, 3)
cat_dim0 = torch.cat((tensor_a, tensor_b), dim=0)
print(f"Concatenated along dim=0 (Shape: {cat_dim0.shape}):\n{cat_dim0}\n")

# Concatenate along dimension 1 (columns)
# Tensors must match in other dimensions (dim 0)
# Resulting shape: (2, 3+3) = (2, 6)
cat_dim1 = torch.cat((tensor_a, tensor_b), dim=1)
print(f"Concatenated along dim=1 (Shape: {cat_dim1.shape}):\n{cat_dim1}")

# Example with 3D tensors
tensor_c = torch.randn(1, 2, 3)
tensor_d = torch.randn(1, 2, 3)
# Concatenate along dim 0 (batch dimension)
# Resulting shape: (1+1, 2, 3) = (2, 2, 3)
cat_3d_dim0 = torch.cat((tensor_c, tensor_d), dim=0)
print(f"\nConcatenated 3D along dim=0 (Shape: {cat_3d_dim0.shape})")


Tensor A (Shape: torch.Size([2, 3])):
tensor([[ 1.4365, -0.6825, -0.3008],
        [ 0.2079,  0.6666,  0.1109]])
Tensor B (Shape: torch.Size([2, 3])):
tensor([[-0.5251,  0.4559, -0.1600],
        [ 0.2853, -1.0600, -1.0278]])

Concatenated along dim=0 (Shape: torch.Size([4, 3])):
tensor([[ 1.4365, -0.6825, -0.3008],
        [ 0.2079,  0.6666,  0.1109],
        [-0.5251,  0.4559, -0.1600],
        [ 0.2853, -1.0600, -1.0278]])

Concatenated along dim=1 (Shape: torch.Size([2, 6])):
tensor([[ 1.4365, -0.6825, -0.3008, -0.5251,  0.4559, -0.1600],
        [ 0.2079,  0.6666,  0.1109,  0.2853, -1.0600, -1.0278]])

Concatenated 3D along dim=0 (Shape: torch.Size([2, 2, 3]))


In [8]:
import torch

# Create two tensors with the same shape
tensor_e = torch.arange(6).reshape(2, 3)
tensor_f = torch.arange(6, 12).reshape(2, 3)
print(f"Tensor E (Shape: {tensor_e.shape}):\n{tensor_e}")
print(f"Tensor F (Shape: {tensor_f.shape}):\n{tensor_f}\n")

# Stack along a new dimension 0
# Resulting shape: (2, 2, 3)
stack_dim0 = torch.stack((tensor_e, tensor_f), dim=0)
print(f"Stacked along new dim=0 (Shape: {stack_dim0.shape}):\n{stack_dim0}\n")

# Stack along a new dimension 1
# Resulting shape: (2, 2, 3)
stack_dim1 = torch.stack((tensor_e, tensor_f), dim=1)
print(f"Stacked along new dim=1 (Shape: {stack_dim1.shape}):\n{stack_dim1}\n")

# Stack along a new dimension 2 (last dimension)
# Resulting shape: (2, 3, 2)
stack_dim2 = torch.stack((tensor_e, tensor_f), dim=2)
print(f"Stacked along new dim=2 (Shape: {stack_dim2.shape}):\n{stack_dim2}")


Tensor E (Shape: torch.Size([2, 3])):
tensor([[0, 1, 2],
        [3, 4, 5]])
Tensor F (Shape: torch.Size([2, 3])):
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

Stacked along new dim=0 (Shape: torch.Size([2, 2, 3])):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

Stacked along new dim=1 (Shape: torch.Size([2, 2, 3])):
tensor([[[ 0,  1,  2],
         [ 6,  7,  8]],

        [[ 3,  4,  5],
         [ 9, 10, 11]]])

Stacked along new dim=2 (Shape: torch.Size([2, 3, 2])):
tensor([[[ 0,  6],
         [ 1,  7],
         [ 2,  8]],

        [[ 3,  9],
         [ 4, 10],
         [ 5, 11]]])


In [9]:
import torch

# Create a tensor to split
tensor_g = torch.arange(12).reshape(6, 2)
print(f"Original Tensor (Shape: {tensor_g.shape}):\n{tensor_g}\n")

# Split into chunks of size 2 along dimension 0 (rows)
# 6 rows / 2 rows/chunk = 3 chunks
split_equal = torch.split(tensor_g, 2, dim=0)
print("Split into equal chunks of size 2 (dim=0):")
for i, chunk in enumerate(split_equal):
    print(f" Chunk {i} (Shape: {chunk.shape}):\n{chunk}")

print("-" * 20)

# Split into chunks of sizes [1, 2, 3] along dimension 0
# Total size must sum to the dimension size (1 + 2 + 3 = 6)
split_unequal = torch.split(tensor_g, [1, 2, 3], dim=0)
print("\nSplit into unequal chunks [1, 2, 3] (dim=0):")
for i, chunk in enumerate(split_unequal):
    print(f" Chunk {i} (Shape: {chunk.shape}):\n{chunk}")

print("-" * 20)

# Split along dimension 1 (columns)
# Shape: (6, 2). Split into chunks of size 1 along dim=1
split_dim1 = torch.split(tensor_g, 1, dim=1)
print("\nSplit into equal chunks of size 1 (dim=1):")
for i, chunk in enumerate(split_dim1):
    # Using squeeze removes the dimension of size 1 for clearer display
    print(f" Chunk {i} (Shape: {chunk.shape}):\n{chunk.squeeze()}")



Original Tensor (Shape: torch.Size([6, 2])):
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

Split into equal chunks of size 2 (dim=0):
 Chunk 0 (Shape: torch.Size([2, 2])):
tensor([[0, 1],
        [2, 3]])
 Chunk 1 (Shape: torch.Size([2, 2])):
tensor([[4, 5],
        [6, 7]])
 Chunk 2 (Shape: torch.Size([2, 2])):
tensor([[ 8,  9],
        [10, 11]])
--------------------

Split into unequal chunks [1, 2, 3] (dim=0):
 Chunk 0 (Shape: torch.Size([1, 2])):
tensor([[0, 1]])
 Chunk 1 (Shape: torch.Size([2, 2])):
tensor([[2, 3],
        [4, 5]])
 Chunk 2 (Shape: torch.Size([3, 2])):
tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
--------------------

Split into equal chunks of size 1 (dim=1):
 Chunk 0 (Shape: torch.Size([6, 1])):
tensor([ 0,  2,  4,  6,  8, 10])
 Chunk 1 (Shape: torch.Size([6, 1])):
tensor([ 1,  3,  5,  7,  9, 11])


In [10]:
import torch

# Create a tensor
tensor_h = torch.arange(10).reshape(5, 2) # Size 5 along dim 0
print(f"Original Tensor (Shape: {tensor_h.shape}):\n{tensor_h}\n")

# Split into 3 chunks along dimension 0
# 5 rows / 3 chunks -> sizes will be [2, 2, 1] ( ceil(5/3)=2 for first chunks)
chunked_tensor = torch.chunk(tensor_h, 3, dim=0)
print("Chunked into 3 parts (dim=0):")
for i, chunk in enumerate(chunked_tensor):
    print(f" Chunk {i} (Shape: {chunk.shape}):\n{chunk}")

print("-" * 20)

# Create another tensor
tensor_i = torch.arange(12).reshape(3, 4) # Size 4 along dim 1
print(f"\nOriginal Tensor (Shape: {tensor_i.shape}):\n{tensor_i}\n")

# Split into 2 chunks along dimension 1
# 4 cols / 2 chunks -> sizes will be [2, 2] ( ceil(4/2)=2 )
chunked_tensor_dim1 = torch.chunk(tensor_i, 2, dim=1)
print("Chunked into 2 parts (dim=1):")
for i, chunk in enumerate(chunked_tensor_dim1):
    print(f" Chunk {i} (Shape: {chunk.shape}):\n{chunk}")



Original Tensor (Shape: torch.Size([5, 2])):
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

Chunked into 3 parts (dim=0):
 Chunk 0 (Shape: torch.Size([2, 2])):
tensor([[0, 1],
        [2, 3]])
 Chunk 1 (Shape: torch.Size([2, 2])):
tensor([[4, 5],
        [6, 7]])
 Chunk 2 (Shape: torch.Size([1, 2])):
tensor([[8, 9]])
--------------------

Original Tensor (Shape: torch.Size([3, 4])):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Chunked into 2 parts (dim=1):
 Chunk 0 (Shape: torch.Size([3, 2])):
tensor([[0, 1],
        [4, 5],
        [8, 9]])
 Chunk 1 (Shape: torch.Size([3, 2])):
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Understanding Broadcasting

In [11]:
import torch

# Tensor A: Shape [2, 3]
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Scalar B: Shape [] (0 dimensions)
b = torch.tensor(10)

# Add scalar to tensor
c = a + b

print(f"Shape of a: {a.shape}")
# Shape of a: torch.Size([2, 3])
print(f"Shape of b: {b.shape}")
# Shape of b: torch.Size([])
print(f"Shape of c: {c.shape}")
# Shape of c: torch.Size([2, 3])
print(f"Result c:\n{c}")
# Result c:
# tensor([[11, 12, 13],
#         [14, 15, 16]])


Shape of a: torch.Size([2, 3])
Shape of b: torch.Size([])
Shape of c: torch.Size([2, 3])
Result c:
tensor([[11, 12, 13],
        [14, 15, 16]])


In [12]:
# Tensor A: Shape [2, 3]
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
# Tensor B: Shape [3] (can be seen as [1, 3] for broadcasting)
b = torch.tensor([10, 20, 30])

# Add row vector to matrix
c = a + b

print(f"Shape of a: {a.shape}") # torch.Size([2, 3])
print(f"Shape of b: {b.shape}") # torch.Size([3])
print(f"Shape of c: {c.shape}") # torch.Size([2, 3])
print(f"Result c:\n{c}")
# Result c:
# tensor([[11, 22, 33],
#         [14, 25, 36]])


Shape of a: torch.Size([2, 3])
Shape of b: torch.Size([3])
Shape of c: torch.Size([2, 3])
Result c:
tensor([[11, 22, 33],
        [14, 25, 36]])


In [13]:
# Tensor A: Shape [2, 3]
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
# Tensor B: Shape [2, 1]
b = torch.tensor([[10], [20]])

# Add column vector to matrix
c = a + b

print(f"Shape of a: {a.shape}") # torch.Size([2, 3])
print(f"Shape of b: {b.shape}") # torch.Size([2, 1])
print(f"Shape of c: {c.shape}") # torch.Size([2, 3])
print(f"Result c:\n{c}")
# Result c:
# tensor([[11, 12, 13],
#         [24, 25, 26]])


Shape of a: torch.Size([2, 3])
Shape of b: torch.Size([2, 1])
Shape of c: torch.Size([2, 3])
Result c:
tensor([[11, 12, 13],
        [24, 25, 26]])


In [14]:
# Tensor A: Shape [2, 3]
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Tensor B: Shape [2]
b = torch.tensor([10, 20])

try:
    c = a + b
except RuntimeError as e:
    print(f"Error: {e}")
# Error: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


Error: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


# Tensor Data Types

In [15]:
import torch

# Default float tensor
a = torch.tensor([1.0, 2.0, 3.0])
print(f"Tensor a: {a}")
print(f"dtype of a: {a.dtype}")

# Default integer tensor
b = torch.tensor([1, 2, 3])
print(f"\nTensor b: {b}")
print(f"dtype of b: {b.dtype}")


Tensor a: tensor([1., 2., 3.])
dtype of a: torch.float32

Tensor b: tensor([1, 2, 3])
dtype of b: torch.int64


In [16]:
# Create a tensor with 64-bit floating point numbers
c = torch.tensor([1.0, 2.0], dtype=torch.float64)
print(f"\nTensor c: {c}")
print(f"dtype of c: {c.dtype}")

# Create a tensor with 32-bit integers
d = torch.ones(2, 2, dtype=torch.int32)
print(f"\nTensor d:\n{d}")
print(f"dtype of d: {d.dtype}")



Tensor c: tensor([1., 2.], dtype=torch.float64)
dtype of c: torch.float64

Tensor d:
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
dtype of d: torch.int32


In [17]:
float_tensor = torch.tensor([1.1, 2.2, 3.3], dtype=torch.float32)
print(f"Original tensor: {float_tensor}, dtype: {float_tensor.dtype}")

# Cast to int64 using .to()
int_tensor = float_tensor.to(torch.int64)
print(f"Casted to int64: {int_tensor}, dtype: {int_tensor.dtype}") # Note the truncation

# Cast back to float16 using .to()
half_tensor = int_tensor.to(dtype=torch.float16) # Can specify only dtype
print(f"Casted to float16: {half_tensor}, dtype: {half_tensor.dtype}")


Original tensor: tensor([1.1000, 2.2000, 3.3000]), dtype: torch.float32
Casted to int64: tensor([1, 2, 3]), dtype: torch.int64
Casted to float16: tensor([1., 2., 3.], dtype=torch.float16), dtype: torch.float16
